# The config file supports color codes. For example gold is &6
# More specific information about the config file here: https://modrinth.com/plugin/automatic-crafting-table

enabled: true
crafting-table-ui-display: 'Automatic Crafting Table Recipe'
crafting-table-timer: 4
crafting-table-visual-feedback-enabled: true
crafting-table-sound-feedback-enabled: true
separate-from-other-crafting-tables: false
automatic-crafting-table-item-display: "&aAutomatic-Crafting-Table"
automatic-crafting-table-item-lore:
  - "&eUse this Crafting Table in a "
  - "&ehopper system to automatically "
  - "&ecraft items"