# The config file supports color codes. For example gold is &6

enabled: true
crafting-table-ui-display: 'Automatic Crafting Table Recipe'
crafting-table-ui-space-display: 'space'
crafting-table-timer: 4 # In ticks. 20 ticks = 1 second